Repository work-at/backend, pull requests merged in 2022-08, with the labels that each got.

#87 Feature/mypage qna
  src/main/java/com/workat/api/map/dto/WorkerDto.java
  src/main/java/com/workat/api/report/controller/ReportController.java
  src/main/java/com/workat/api/report/dto/request/ReportRequest.java
  src/main/java/com/workat/api/report/service/ReportService.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/response/MyProfileResponse.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/report/CSType.java
  src/main/java/com/workat/domain/report/entity/Report.java
  src/main/java/com/workat/domain/report/repository/ReportRepository.java
  src/main/java/com/workat/domain/user/filter/FilterEmail.java
Labels: enhancement

#88 Refactor/profile image path
  src/main/java/com/workat/api/report/dto/request/ReportRequest.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: enhancement

#97 ReviewType 에 iconType 제거
  src/main/java/com/workat/api/review/dto/ReviewTypeDto.java
  src/main/java/com/workat/domain/review/BaseReviewType.java
  src/main/java/com/workat/domain/review/CafeReviewType.java
  src/main/java/com/workat/domain/review/FoodReviewType.java
Labels: refactor

#100 review enum 을 tag 패키지로 분리
  src/main/java/com/workat/api/review/dto/ReviewDto.java
  src/main/java/com/workat/api/review/dto/ReviewTypeDto.java
  src/main/java/com/workat/api/review/service/CollectReviewTypeService.java
  src/main/java/com/workat/api/review/service/ReviewService.java
  src/main/java/com/workat/domain/review/BaseReviewType.java
  src/main/java/com/workat/domain/review/entity/BaseReview.java
  src/main/java/com/workat/domain/review/entity/CafeReview.java
  src/main/java/com/workat/domain/review/entity/RestaurantReview.java
  src/main/java/com/workat/domain/tag/BaseTag.java
  src/main/java/com/workat/domain/tag/CafeReviewType.java
  src/main/java/com/workat/domain/tag/FoodReviewType.java
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
Labels: refactor

#101 domain/review -> domain/locationReview 로 패키지 네이밍 변경
  src/main/java/com/workat/api/review/service/ReviewService.java
  src/main/java/com/workat/domain/locationReview/entity/BaseReview.java
  src/main/java/com/workat/domain/locationReview/entity/CafeReview.java
  src/main/java/com/workat/domain/locationReview/entity/RestaurantReview.java
  src/main/java/com/workat/domain/locationReview/repository/CafeReviewRepository.java
  src/main/java/com/workat/domain/locationReview/repository/RestaurantReviewRepository.java
  src/test/java/com/workat/api/map/service/LocationServiceTest.java
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
Labels: refactor

#105 Feature/tour api
  src/main/java/com/workat/api/tour/BigDataLocalResponse.java
  src/main/java/com/workat/api/tour/BigDataMetroResponse.java
  src/main/java/com/workat/api/tour/dto/VisitorDegree.java
  src/main/java/com/workat/api/tour/model/BigDataResponse.java
  src/main/java/com/workat/api/tour/model/BigDataResponseBody.java
  src/main/java/com/workat/api/tour/model/BigDataResponseHeader.java
  src/main/java/com/workat/api/tour/model/BigDataResponseItem.java
  src/main/java/com/workat/api/tour/model/BigDataResponseItems.java
  src/main/java/com/workat/api/tour/service/TourApiService.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/common/util/ExternalApiCallUtils.java
  src/main/java/com/workat/domain/tour/RegionCode.java
  src/main/java/com/workat/domain/tour/entity/MonthlyRegionVisitor.java
  src/main/java/com/workat/domain/tour/entity/YearlyRegionVisitor.java
  src/main/java/com/workat/domain/tour/repository/MonthlyRegionVisitorRepository.java
  src/main/java/com/workat/domain/tour/repository/YearlyRegionVisitorRepository.java
  src/main/java/com/workat/domain/user/job/DepartmentType.java
  src/test/java/com/workat/api/chat/service/ChatServiceTest.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/api/map/service/LocationServiceTest.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
  src/test/java/com/workat/common/util/ExternalApiCallUtilsTest.java
Labels: enhancement, refactor

#110 숙소 태그 조회 API 개발
  src/main/java/com/workat/api/accommodation/controller/AccommodationTagController.java
  src/main/java/com/workat/api/accommodation/dto/response/TagsResponse.java
  src/main/java/com/workat/api/accommodation/service/CollectAccommodationTagService.java
  src/main/java/com/workat/domain/tag/AccommodationInfoTag.java
  src/main/java/com/workat/domain/tag/AccommodationReviewTag.java
  src/main/java/com/workat/domain/tag/dto/TagDto.java
Labels: enhancement

#111 숙소 복수건 조회 Mock API 추가
  src/main/java/com/workat/api/accommodation/controller/AccommodationController.java
  src/main/java/com/workat/api/accommodation/dto/AccommodationDto.java
  src/main/java/com/workat/api/accommodation/dto/response/AccommodationsResponse.java
  src/main/java/com/workat/api/accommodation/service/AccommodationService.java
  src/main/java/com/workat/domain/accommodation/RegionType.java
Labels: enhancement

#112 숙소 단건 조회 Mock API 추가
  src/main/java/com/workat/api/accommodation/controller/AccommodationController.java
  src/main/java/com/workat/api/accommodation/dto/AccommodationDetailDto.java
  src/main/java/com/workat/api/accommodation/dto/AccommodationReviewDto.java
  src/main/java/com/workat/api/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/workat/api/accommodation/service/AccommodationService.java
  src/main/java/com/workat/domain/tag/dto/TagWithCountDto.java
Labels: enhancement

#113 add ssl certificate key store
  src/main/resources/application-prod.yml
Labels: enhancement

#118 fix: redirect url 변경
  src/main/resources/application-prod.yml
Labels: bug

#123 채팅방 중복 생성 수정, 자기 자신과 채팅방 만들 수 없게 수정
  src/main/java/com/workat/api/chat/service/ChatService.java
  src/main/java/com/workat/domain/chat/entity/ChatRoom.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/test/java/com/workat/api/chat/service/ChatServiceTest.java
Labels: enhancement

#124 Feature/tour data api
  src/main/java/com/workat/api/review/dto/response/ReviewTypeListResponse.java
  src/main/java/com/workat/api/tour/controller/RegionTrafficController.java
  src/main/java/com/workat/api/tour/dto/VisitorDegree.java
  src/main/java/com/workat/api/tour/dto/response/RegionTrafficResponse.java
  src/main/java/com/workat/api/tour/service/TourApiService.java
  src/main/java/com/workat/domain/accommodation/RegionType.java
  src/main/java/com/workat/domain/tour/RegionCode.java
  src/main/java/com/workat/domain/tour/entity/MonthlyRegionVisitor.java
  src/main/java/com/workat/domain/tour/entity/YearlyRegionVisitor.java
Labels: enhancement

#130 식당 리뷰 이슈 해결
  src/main/java/com/workat/api/map/controller/LocationController.java
Labels: bug

#133 리뷰 연속 POST 시 500 에러
  src/main/java/com/workat/api/review/service/ReviewService.java
Labels: bug

#135 리뷰 연속 POST 시 500 에러
  src/main/java/com/workat/api/review/service/ReviewService.java
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
Labels: bug

#145 숙소 단건 조회 API 추가
  src/main/java/com/workat/api/accommodation/controller/AccommodationController.java
  src/main/java/com/workat/api/accommodation/dto/AccommodationDetailDto.java
  src/main/java/com/workat/api/accommodation/dto/AccommodationReviewDto.java
  src/main/java/com/workat/api/accommodation/service/AccommodationService.java
  src/main/java/com/workat/domain/accommodation/entity/Accommodation.java
  src/main/java/com/workat/domain/accommodation/entity/AccommodationInfo.java
  src/main/java/com/workat/domain/accommodation/entity/AccommodationReview.java
  src/main/java/com/workat/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/workat/domain/accommodation/repository/AccommodationReviewRepository.java
  src/main/java/com/workat/domain/tag/dto/TagCountDto.java
  src/test/java/com/workat/api/accommodation/service/AccommodationServiceTest.java
Labels: enhancement

#147 fix: 유저 액티비티 중복 저장 오류 수정
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/response/MyProfileResponse.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/user/repository/UserActivityRepository.java
Labels: bug
