Repository work-at/backend, pull requests merged in 2022-09, with the labels that each got.

#152 refactor: 지역 혼잡도 조회 시 리퀘스트 파라미터 추가
  src/main/java/com/workat/api/tour/controller/RegionTrafficController.java
Labels: refactor

#158 테스트 계정 로그인 API 추가
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/auth/dto/request/TestTokenRequest.java
  src/main/java/com/workat/api/auth/service/AuthorizationService.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/auth/OauthType.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/main/java/com/workat/domain/user/repository/UsersRepository.java
Labels: enhancement

#156 유저 프로필 필수 컬럼 값 validation 추가
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/auth/dto/request/TestTokenRequest.java
  src/main/java/com/workat/api/auth/service/AuthorizationService.java
  src/main/java/com/workat/api/user/dto/request/SignUpRequest.java
  src/main/java/com/workat/api/user/dto/request/UserUpdateRequest.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/auth/OauthType.java
  src/main/java/com/workat/domain/user/entity/UserProfile.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/main/java/com/workat/domain/user/repository/UsersRepository.java
Labels: enhancement

#160 fix: null 일때 처리
  src/main/java/com/workat/api/map/dto/WorkerDto.java
  src/main/java/com/workat/api/user/dto/response/MyProfileResponse.java
Labels: bug

#165 mysql 예약어로 인한 쿼리 에러
  src/main/java/com/workat/domain/accommodation/entity/Accommodation.java
Labels: bug

#167 숙소 복수건 info tag 필터링 조회
  src/main/java/com/workat/domain/accommodation/repository/AccommodationRepository.java
Labels: bug

#169 test: test 수정
  src/test/java/com/workat/api/accommodation/service/AccommodationServiceTest.java
Labels: bug

#173 숙소 리뷰 태그 관련 수정
  src/main/java/com/workat/api/accommodation/dto/AccommodationDto.java
  src/main/java/com/workat/api/accommodation/dto/AccommodationReviewDto.java
  src/main/java/com/workat/api/accommodation/service/AccommodationService.java
  src/main/java/com/workat/domain/accommodation/repository/AccommodationReviewRepository.java
  src/test/java/com/workat/api/accommodation/service/AccommodationServiceTest.java
Labels: enhancement

#174 fix: email 리셋
  src/main/java/com/workat/api/user/service/UserService.java
Labels: bug
