Repository work-at/backend, pull requests merged in 2022-07, with the labels that each got.

#20 Feature/kako loacal address
  src/main/java/com/workat/api/map/service/AddressService.java
  src/main/java/com/workat/api/map/service/LocationService.java
  src/main/java/com/workat/api/tour/model/BigDataResponse.java
  src/main/java/com/workat/api/tour/model/BigDataResponseBody.java
  src/main/java/com/workat/api/tour/model/BigDataResponseHeader.java
  src/main/java/com/workat/common/config/SwaggerConfig.java
  src/main/java/com/workat/common/exception/ExternalApiException.java
  src/main/java/com/workat/common/exception/handler/RestTemplateExceptionHandler.java
  src/main/java/com/workat/common/util/ExternalApiCallUtils.java
  src/main/java/com/workat/domain/map/entity/WorkerLocation.java
  src/main/java/com/workat/domain/map/http/LocationHttpReceiver.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressDocumentDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressMetaDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressResponse.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressRoadDto.java
  src/main/java/com/workat/domain/map/repository/WorkerLocationRedisRepository.java
  src/test/java/com/workat/WorkatApplicationTests.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/common/util/ExternalApiCallUtilsTest.java
  src/test/java/com/workat/domain/map/http/LocationHttpReceiverTest.java
Labels: enhancement

#26 Feature/find near worker size
  build.gradle
  src/main/java/com/workat/api/map/service/WorkChatService.java
  src/main/java/com/workat/domain/map/entity/WorkerLocation.java
  src/main/java/com/workat/domain/map/http/LocationHttpReceiver.java
  src/main/java/com/workat/domain/map/repository/WorkerLocationRedisRepository.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/api/map/service/WorkChatServiceTest.java
  src/test/java/com/workat/domain/config/RedisContainerBaseTest.java
  src/test/java/com/workat/domain/repository/WorkerLocationRedisRepositoryTest.java
Labels: enhancement

#27 Feature/review enum list
  src/main/java/com/workat/api/review/controller/CollectReviewEnumController.java
  src/main/java/com/workat/api/review/dto/ReviewTypeListResponse.java
  src/main/java/com/workat/api/review/dto/ReviewTypeResponse.java
  src/main/java/com/workat/api/review/service/CollectReviewTypeService.java
  src/main/java/com/workat/domain/review/BaseReviewType.java
  src/main/java/com/workat/domain/review/CafeReviewType.java
  src/main/java/com/workat/domain/review/FoodReviewType.java
Labels: enhancement

#29 Refactor/user entity enum field
  src/main/java/com/workat/api/review/controller/CollectReviewTypeController.java
  src/main/java/com/workat/api/review/dto/ReviewTypeResponse.java
  src/main/java/com/workat/api/user/controller/CollectJobTypeController.java
  src/main/java/com/workat/api/user/dto/DepartmentTypeDto.java
  src/main/java/com/workat/api/user/dto/DurationTypeDto.java
  src/main/java/com/workat/api/user/dto/JobTypeDto.java
  src/main/java/com/workat/api/user/dto/JobTypeListResponse.java
  src/main/java/com/workat/api/user/dto/SignUpRequest.java
  src/main/java/com/workat/api/user/service/CollectJobTypeService.java
  src/main/java/com/workat/domain/user/User.java
  src/main/java/com/workat/domain/user/job/DepartmentType.java
  src/main/java/com/workat/domain/user/job/DurationType.java
Labels: enhancement

#31 Feature/near user list
  build.gradle
  src/main/java/com/workat/api/map/dto/WorkerDto.java
  src/main/java/com/workat/api/map/dto/WorkerListResponse.java
  src/main/java/com/workat/api/map/service/AddressService.java
  src/main/java/com/workat/api/map/service/WorkChatService.java
  src/main/java/com/workat/api/user/repository/UserRepository.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/map/entity/WorkerLocation.java
  src/main/java/com/workat/domain/map/repository/WorkerLocationRedisRepository.java
  src/main/java/com/workat/domain/user/Users.java
  src/main/resources/application-test.yml
  src/test/java/com/workat/WorkatApplicationTests.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/api/map/service/LocationServiceTest.java
  src/test/java/com/workat/api/map/service/WorkChatServiceTest.java
  src/test/java/com/workat/domain/config/MultipleDatasourceBaseTest.java
  src/test/java/com/workat/domain/config/MysqlContainerBaseTest.java
  src/test/java/com/workat/domain/repository/WorkerLocationRedisRepositoryTest.java
Labels: enhancement

#34 Feature/near user detail
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/map/controller/LocationBatchController.java
  src/main/java/com/workat/api/map/controller/WorkChatController.java
  src/main/java/com/workat/api/map/dto/WorkerDetailResponse.java
  src/main/java/com/workat/api/map/dto/WorkerListResponse.java
  src/main/java/com/workat/api/map/dto/WorkerResponse.java
  src/main/java/com/workat/api/map/dto/WorkerResponseDetail.java
  src/main/java/com/workat/api/map/service/WorkChatService.java
  src/main/java/com/workat/domain/user/Users.java
  src/test/java/com/workat/api/map/service/WorkChatServiceTest.java
Labels: enhancement

#38 refactor: change naming & clean up import list
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/map/controller/LocationController.java
  src/main/java/com/workat/api/map/controller/MapBatchController.java
  src/main/java/com/workat/api/map/controller/WorkerController.java
  src/main/java/com/workat/api/map/dto/MapLocationDto.java
  src/main/java/com/workat/api/map/dto/WorkerDetailResponse.java
  src/main/java/com/workat/api/map/dto/WorkerDto.java
  src/main/java/com/workat/api/map/dto/request/LocationRequest.java
  src/main/java/com/workat/api/map/dto/request/LocationTriggerRequest.java
  src/main/java/com/workat/api/map/dto/response/LocationResponse.java
  src/main/java/com/workat/api/map/dto/response/WorkerDetailResponse.java
  src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
  src/main/java/com/workat/api/map/service/AddressService.java
  src/main/java/com/workat/api/map/service/LocationService.java
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/main/java/com/workat/api/review/controller/CollectReviewTypeController.java
  src/main/java/com/workat/api/review/dto/ReviewTypeResponse.java
  src/main/java/com/workat/api/review/service/CollectReviewTypeService.java
  src/main/java/com/workat/api/sample/SampleController.java
  src/main/java/com/workat/api/tour/BigDataLocalResponse.java
  src/main/java/com/workat/api/tour/BigDataMetroResponse.java
  src/main/java/com/workat/api/tour/model/BigDataResponseItem.java
  src/main/java/com/workat/api/user/controller/CollectJobTypeController.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/request/SignUpRequest.java
  src/main/java/com/workat/api/user/dto/response/JobTypeListResponse.java
  src/main/java/com/workat/api/user/service/CollectJobTypeService.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/common/config/SwaggerConfig.java
  src/main/java/com/workat/common/util/ExternalApiCallUtils.java
  src/main/java/com/workat/domain/map/entity/Location.java
  src/main/java/com/workat/domain/map/entity/LocationCategory.java
  src/main/java/com/workat/domain/map/http/LocationHttpReceiver.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressDocumentDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressMetaDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoAddressRoadDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoLocalDataDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoLocalMetaDto.java
  src/main/java/com/workat/domain/map/http/dto/KakaoLocalResponse.java
  src/main/java/com/workat/domain/map/repository/WorkerLocationRedisRepository.java
  src/main/java/com/workat/domain/user/Users.java
  src/test/java/com/workat/api/map/service/LocationServiceTest.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
  src/test/java/com/workat/domain/map/http/LocationHttpReceiverTest.java
Labels: refactor

#36 회원/인증 구현
  .github/workflows/git-action.yml
  build.gradle
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/auth/dto/AuthResponse.java
  src/main/java/com/workat/api/auth/dto/KakaoOauthAccessTokenDto.java
  src/main/java/com/workat/api/auth/service/AuthorizationService.java
  src/main/java/com/workat/api/auth/service/KakaoOauthService.java
  src/main/java/com/workat/api/jwt/service/JwtService.java
  src/main/java/com/workat/api/map/dto/MapLocationDto.java
  src/main/java/com/workat/api/map/dto/WorkerDto.java
  src/main/java/com/workat/api/map/dto/response/WorkerDetailResponse.java
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/main/java/com/workat/api/sample/SampleController.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/SignUpResponse.java
  src/main/java/com/workat/api/user/dto/UserDto.java
  src/main/java/com/workat/api/user/dto/request/SignUpRequest.java
  src/main/java/com/workat/api/user/repository/UserRepository.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/common/annotation/UserValidation.java
  src/main/java/com/workat/common/annotation/argumentResolver/UserValidationArgumentResolver.java
  src/main/java/com/workat/common/annotation/aspect/OauthTokenValidationAspect.java
  src/main/java/com/workat/common/config/WebConfig.java
  src/main/java/com/workat/domain/auth/AuthCode.java
  src/main/java/com/workat/domain/map/entity/Location.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/main/java/com/workat/domain/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
Labels: enhancement

#40 docs: swagger
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/auth/dto/AuthResponse.java
  src/main/java/com/workat/api/auth/dto/KakaoOauthTokenRequest.java
  src/main/java/com/workat/api/review/controller/CollectReviewTypeController.java
  src/main/java/com/workat/api/review/dto/ReviewTypeListResponse.java
  src/main/java/com/workat/api/user/controller/CollectJobTypeController.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/SignUpResponse.java
  src/main/java/com/workat/api/user/dto/request/SignUpRequest.java
  src/main/java/com/workat/api/user/dto/response/JobTypeListResponse.java
Labels: documentation

#41 회원/인증 리팩터링
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/auth/dto/request/KakaoOauthTokenRequest.java
  src/main/java/com/workat/api/auth/dto/response/AuthResponse.java
  src/main/java/com/workat/api/auth/dto/response/KakaoOauthTokenInfoResponse.java
  src/main/java/com/workat/api/auth/dto/response/KakaoOauthTokenResponse.java
  src/main/java/com/workat/api/auth/service/KakaoOauthService.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/common/annotation/argumentResolver/UserValidationArgumentResolver.java
  src/main/java/com/workat/domain/user/entity/Users.java
Labels: refactor

#42 fix: supportsParameter UserValidation & validate token
  src/main/java/com/workat/common/annotation/argumentResolver/UserValidationArgumentResolver.java
Labels: bug

#43 Feature/address and worker count controller
  src/main/java/com/workat/api/map/controller/AddressController.java
  src/main/java/com/workat/api/map/controller/WorkerController.java
  src/main/java/com/workat/api/map/dto/WorkerDto.java
  src/main/java/com/workat/api/map/dto/request/NearWorkerCountRequest.java
  src/main/java/com/workat/api/map/dto/response/NearWorkerCountResponse.java
  src/main/java/com/workat/api/map/dto/response/WorkerDetailResponse.java
  src/main/java/com/workat/api/map/service/AddressService.java
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/main/java/com/workat/api/user/dto/DurationTypeDto.java
  src/main/java/com/workat/api/user/dto/request/SignUpRequest.java
  src/main/java/com/workat/api/user/service/CollectJobTypeService.java
  src/main/java/com/workat/domain/map/entity/WorkerLocation.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/main/java/com/workat/domain/user/job/DurationType.java
  src/main/resources/application.yml
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
  src/test/java/com/workat/domain/config/MultipleDatasourceBaseTest.java
  src/test/java/com/workat/domain/config/MysqlContainerBaseTest.java
  src/test/java/com/workat/domain/config/RedisContainerBaseTest.java
Labels: bug, enhancement, refactor

#44 feature: get near workers controller
  src/main/java/com/workat/api/map/controller/WorkerController.java
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
Labels: enhancement

#45 feat: nickname validation
  build.gradle
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/main/java/com/workat/domain/user/repository/UserRepository.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
Labels: enhancement

#48 카카오 로그인 리다이렉트 url 변경
  build.gradle
  src/main/java/com/workat/api/auth/service/KakaoOauthService.java
Labels: enhancement

#47 bugfix: cors 매핑 추가, 닉네임 제약조건 관련하여 테스트 데이터 변경
  src/main/java/com/workat/common/config/WebConfig.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
Labels: bug

#49 ouathId -> oauthId 오타 수정
  src/main/java/com/workat/api/auth/dto/response/AuthResponse.java
  src/main/java/com/workat/api/user/dto/request/SignUpRequest.java
Labels: bug

#50 bugfix: requestparam value mapping
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/user/repository/UsersRepository.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
Labels: bug

#58 카페 리뷰 추가 수정사항
  src/main/java/com/workat/api/auth/controller/AuthorizationController.java
  src/main/java/com/workat/api/map/controller/AddressController.java
  src/main/java/com/workat/api/map/controller/LocationController.java
  src/main/java/com/workat/api/map/controller/MapBatchController.java
  src/main/java/com/workat/api/map/controller/WorkerController.java
  src/main/java/com/workat/api/map/dto/response/CafeDetailResponse.java
  src/main/java/com/workat/api/map/service/LocationService.java
  src/main/java/com/workat/api/review/controller/ReviewController.java
  src/main/java/com/workat/api/review/dto/CafeReviewsDto.java
  src/main/java/com/workat/api/review/dto/request/CafeReviewRequest.java
  src/main/java/com/workat/api/review/service/ReviewService.java
  src/main/java/com/workat/api/user/controller/CollectJobTypeController.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/common/config/SwaggerConfig.java
  src/test/java/com/workat/api/map/service/LocationServiceTest.java
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
Labels: enhancement

#51 Refactor/address save and worker size
  .github/workflows/git-action.yml
  Dockerfile.dev
  src/main/java/com/workat/api/map/controller/AddressController.java
  src/main/java/com/workat/api/map/controller/WorkerController.java
  src/main/java/com/workat/api/map/dto/request/NearWorkerCountRequest.java
  src/main/java/com/workat/api/map/dto/request/UserAddressRequest.java
  src/main/java/com/workat/api/map/dto/response/UserAddressResponse.java
  src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
  src/main/java/com/workat/api/map/dto/response/WorkerSizeResponse.java
  src/main/java/com/workat/api/map/service/AddressService.java
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
Labels: refactor

#53 카페 리뷰 추가
  src/main/java/com/workat/api/map/controller/LocationController.java
  src/main/java/com/workat/api/map/dto/response/CafeDetailResponse.java
  src/main/java/com/workat/api/map/service/LocationService.java
  src/main/java/com/workat/api/review/controller/CollectReviewTypeController.java
  src/main/java/com/workat/api/review/controller/ReviewController.java
  src/main/java/com/workat/api/review/dto/CafeReviewDto.java
  src/main/java/com/workat/api/review/dto/CafeReviewsDto.java
  src/main/java/com/workat/api/review/dto/ReviewTypeDto.java
  src/main/java/com/workat/api/review/dto/request/CafeReviewRequest.java
  src/main/java/com/workat/api/review/dto/response/CafeReviewsResponse.java
  src/main/java/com/workat/api/review/dto/response/ReviewTypeListResponse.java
  src/main/java/com/workat/api/review/service/CollectReviewTypeService.java
  src/main/java/com/workat/api/review/service/ReviewService.java
  src/main/java/com/workat/domain/review/CafeReviewType.java
  src/main/java/com/workat/domain/review/entity/CafeReview.java
  src/main/java/com/workat/domain/review/repository/CafeReviewRepository.java
  src/main/java/com/workat/domain/user/repository/UsersRepository.java
  src/test/java/com/workat/api/map/service/LocationServiceTest.java
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
Labels: enhancement

#65 Refactor/split users userprofile entity
  src/main/java/com/workat/api/map/controller/WorkerController.java
  src/main/java/com/workat/api/map/dto/WorkerDto.java
  src/main/java/com/workat/api/map/dto/response/WorkerDetailResponse.java
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/request/SignUpRequest.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/common/config/JpaConfig.java
  src/main/java/com/workat/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/workat/domain/BaseEntity.java
  src/main/java/com/workat/domain/map/entity/Location.java
  src/main/java/com/workat/domain/review/entity/BaseReview.java
  src/main/java/com/workat/domain/user/entity/UserProfile.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/main/java/com/workat/domain/user/repository/UserProfileRepository.java
  src/main/java/com/workat/domain/user/repository/UsersRepository.java
  src/test/java/com/workat/api/map/service/AddressServiceTest.java
  src/test/java/com/workat/api/map/service/LocationServiceTest.java
  src/test/java/com/workat/api/map/service/WorkerServiceTest.java
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
Labels: refactor

#67 feat: 이미지 업로드 api 추가
  build.gradle
  src/main/java/com/workat/api/mypage/controller/MyPageController.java
  src/main/java/com/workat/api/mypage/service/MyPageService.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/request/UserUpdateRequest.java
  src/main/java/com/workat/api/user/dto/response/MyProfileResponse.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/common/config/WebConfig.java
  src/main/java/com/workat/common/exception/FileUploadException.java
  src/main/java/com/workat/common/util/FileUploadUtils.java
  src/main/java/com/workat/domain/review/CafeReviewType.java
  src/main/java/com/workat/domain/review/FoodReviewType.java
  src/main/java/com/workat/domain/user/entity/UserProfile.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/workat/api/review/service/ReviewServiceTest.java
Labels: enhancement

#72 feat: 메일 인증 api 추가
  build.gradle
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/request/EmailCertifyRequest.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/user/entity/UserProfile.java
  src/main/java/com/workat/domain/user/entity/Users.java
  src/main/java/com/workat/domain/user/repository/UsersRepository.java
  src/main/resources/application.yml
Labels: enhancement

#74 login 리다이렉트 url 변경
  src/main/java/com/workat/api/auth/service/KakaoOauthService.java
Labels: enhancement

#75 feat: 메일 횟수 제한
  src/main/java/com/workat/api/map/controller/WorkerController.java
  src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
  src/main/java/com/workat/api/map/dto/response/WorkerPinResponse.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/response/EmailLimitResponseDto.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/user/entity/UserProfile.java
  src/main/java/com/workat/domain/user/entity/Users.java
Labels: enhancement

#83 Feat/hide my location
  src/main/java/com/workat/api/map/service/WorkerService.java
  src/main/java/com/workat/api/user/controller/UserController.java
  src/main/java/com/workat/api/user/dto/response/MyProfileResponse.java
  src/main/java/com/workat/api/user/service/UserService.java
  src/main/java/com/workat/domain/user/entity/Users.java
Labels: enhancement
